export const CHANGE_TEXT = "CHANGE_TEXT";

export const CREATE_ITEM = "CREATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";

export const REQUEST_DOG = "REQUEST_DOG";
export const REQUEST_DOG_SUCCEEDED = "REQUEST_DOG_SUCCEEDED";
export const REQUEST_DOG_FAILED = "REQUEST_DOG_FAILED";